[assembly: System.CLSCompliant(true)]
[assembly: AssemblyTitle("Diffa")]
[assembly: AssemblyProduct("Diffa")]
[assembly: AssemblyCompany("Ackara")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyCopyright("MIT License")]
[assembly: AssemblyInformationalVersion("1.0.0")]
[assembly: AssemblyFileVersion("1.0.0")]
[assembly: AssemblyVersion("1.0.0")]
